name: Generar tabla te칩rica de descuento

on:
  schedule:
    - cron: '0 7 * * 1'  # Cada lunes a las 7am UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Crear archivo .env con credenciales
      run: |
        echo "XERENITY_USER=${{ secrets.XERENITY_USER }}" >> .env
        echo "XERENITY_PASS=${{ secrets.XERENITY_PASS }}" >> .env

    - name: Ejecutar script de generaci칩n
      run: python scripts/generar_tabla.py

    - name: Subir imagen generada
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Actualizaci칩n autom치tica de imagen tabla_teorica_descuento.jpg"
        file_pattern: assets/tabla_teorica_descuento.jpg

