name: Generar tabla teórica de descuento

on:
  schedule:
    - cron: '0 7 * * 1'  # Cada lunes a las 7am UTC
  workflow_dispatch:

permissions:
  contents: write  # 🔑 Necesario para que el bot pueda hacer push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Crear archivo .env con credenciales
      run: |
        echo "XERENITY_USER=${{ secrets.XERENITY_USER }}" >> .env
        echo "XERENITY_PASS=${{ secrets.XERENITY_PASS }}" >> .env

    - name: Ejecutar script de generación
      run: python main.py

    - name: Subir imagen generada
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Actualización automática de imagen tabla_teorica_descuento.jpg"
        file_pattern: assets/tabla_teorica_descuento.jpg
        commit_user_name: Andres Velez
        commit_user_email: andres.velez@uniandes.edu.co
        commit_author: Andres Velez <andres.velez@uniandes.edu.co>

